# This workflow will generate docs for alpa.

name: Docs

on:
  push:
    branches:
      - main
      - 'hao-wheel*'
  pull_request:
    branches: [ main ]

jobs:
  build_docs:
    runs-on: [self-hosted, alpa]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Test runner
        run:
          nvidia-smi >> report.md
#      - name: Build and install train package
#        run: |
#          pip install -e ./adaptdl
#      - name: Build and install api dependencies
#        run: |
#          pip install torch torchtext
#      - name: Install sphinx
#        run: |
#          pip install sphinx sphinx-rtd-theme
#      - name: Build docs
#        run: |
#          cd docs && make html
#      - name: Upload docs
#        uses: actions/upload-artifact@v1
#        with:
#          name: DocumentationHTML
#          path: docs/_build/html/